<?php
declare(strict_types=1);
require_once __DIR__.'/config.php';require_login();require_once __DIR__.'/includes/layout.php';
$user=current_user();$userId=(int)$user['id'];$limit=(int)($user['sodium_personal_account_limit']??0);
$csv=static fn(string $value):array=>array_values(array_unique(array_filter(array_map(static fn($item)=>strtolower(trim($item)),explode(',',$value)))));
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(($_POST['action']??'')==='delete'){$id=(int)($_POST['id']??0);$stmt=$pdo->prepare('SELECT icon_path FROM sodium_mail_accounts WHERE id=? AND created_by_user_id=? AND is_user_managed=1');$stmt->execute([$id,$userId]);$icon=$stmt->fetchColumn();if($icon!==false){$pdo->prepare('DELETE FROM sodium_user_mail_accounts WHERE mail_account_id=?')->execute([$id]);$pdo->prepare('DELETE FROM sodium_mail_accounts WHERE id=? AND created_by_user_id=?')->execute([$id,$userId]);if($icon&&str_starts_with((string)$icon,'/uploads/mail-icons/'))@unlink(__DIR__.(string)$icon);flash('success','Compte personnel supprimé.');}redirect('/mail-accounts.php');}
    if($limit<1){flash('danger','Vous n’êtes pas autorisé à ajouter un compte mail.');redirect('/mail-accounts.php');}
    $count=$pdo->prepare('SELECT COUNT(*) FROM sodium_mail_accounts WHERE created_by_user_id=? AND is_user_managed=1');$count->execute([$userId]);if((int)$count->fetchColumn()>=$limit){flash('danger','Vous avez atteint le nombre maximal de comptes autorisés.');redirect('/mail-accounts.php');}
    $email=strtolower(trim((string)($_POST['email_address']??'')));$domain=strtolower((string)substr(strrchr($email,'@')?:'',1));
    if(!filter_var($email,FILTER_VALIDATE_EMAIL)){flash('danger','Adresse mail invalide.');redirect('/mail-accounts.php');}
    $exists=$pdo->prepare('SELECT COUNT(*) FROM sodium_mail_accounts WHERE LOWER(email_address)=?');$exists->execute([$email]);if($exists->fetchColumn()){flash('warning','Ce compte existe déjà dans Sodium. Contactez l’administrateur pour demander son utilisation.');redirect('/mail-accounts.php');}
    $banned=$pdo->prepare('SELECT COUNT(*) FROM sodium_banned_mail_addresses WHERE email_address=?');$banned->execute([$email]);
    if($banned->fetchColumn()||in_array($domain,$csv((string)($user['sodium_personal_excluded_domains']??'')),true)||in_array($email,$csv((string)($user['sodium_personal_excluded_addresses']??'')),true)){flash('danger','Cette adresse ou ce domaine n’est pas autorisé.');redirect('/mail-accounts.php');}
    $password=(string)($_POST['password']??'');if($password===''){flash('danger','Le mot de passe est obligatoire.');redirect('/mail-accounts.php');}
    $encryption=static fn(string $value):string=>in_array($value,['ssl','tls','none'],true)?$value:'ssl';
    try{$pdo->beginTransaction();$stmt=$pdo->prepare('INSERT INTO sodium_mail_accounts(email_address,display_name,imap_host,imap_port,imap_encryption,smtp_host,smtp_port,smtp_encryption,login_name,account_status,label_text,label_color,password_cipher,created_by_user_id,is_user_managed) VALUES(?,?,?,?,?,?,?,?,?,\'active\',?,?,?, ?,1)');$stmt->execute([$email,trim((string)($_POST['display_name']??'')),trim((string)($_POST['imap_host']??'')),max(1,min(65535,(int)($_POST['imap_port']??993))),$encryption((string)($_POST['imap_encryption']??'ssl')),trim((string)($_POST['smtp_host']??'')),max(1,min(65535,(int)($_POST['smtp_port']??465))),$encryption((string)($_POST['smtp_encryption']??'ssl')),trim((string)($_POST['login_name']??''))?:$email,mb_substr(trim((string)($_POST['label_text']??'')),0,60),'#0d6efd',sodium_encrypt_secret($password),$userId]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO sodium_user_mail_accounts(user_id,mail_account_id,can_read,can_send,can_manage,is_default) VALUES(?,?,1,1,1,0)')->execute([$userId,$id]);$pdo->commit();flash('success','Compte personnel ajouté.');}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();error_log('[Sodium personal account] '.$error->getMessage());flash('danger','Le compte n’a pas pu être ajouté.');}redirect('/mail-accounts.php');
}
$assigned=$pdo->prepare('SELECT a.* FROM sodium_mail_accounts a JOIN sodium_user_mail_accounts ua ON ua.mail_account_id=a.id WHERE ua.user_id=? AND (a.is_user_managed=0 OR a.created_by_user_id<>?) ORDER BY a.display_name,a.email_address');$assigned->execute([$userId,$userId]);$assigned=$assigned->fetchAll();
$personal=$pdo->prepare('SELECT * FROM sodium_mail_accounts WHERE created_by_user_id=? AND is_user_managed=1 ORDER BY display_name,email_address');$personal->execute([$userId]);$personal=$personal->fetchAll();
sodium_render_header('Comptes mails');
?>
<div class="d-flex justify-content-between align-items-center mb-3"><p class="text-muted mb-0"><?=$limit?count($personal).' / '.$limit.' comptes personnels utilisés':'Ajout personnel non autorisé'?></p><?php if($limit>count($personal)):?><button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#personalAccountModal"><i class="bi bi-plus-lg"></i> Ajouter</button><?php endif;?></div>
<?php foreach(['Comptes attribués par l’administrateur'=>$assigned,'Mes comptes personnels'=>$personal] as $title=>$rows):?><div class="table-card mb-4"><div class="p-3 border-bottom"><h2 class="h6 mb-0"><?=e($title)?></h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Compte</th><th>Statut</th><th></th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="3" class="text-center text-muted py-4">Aucun compte.</td></tr><?php endif;?><?php foreach($rows as $account):?><tr><td><strong><?=e($account['display_name']?:$account['email_address'])?></strong><small class="d-block text-muted"><?=e($account['email_address'])?></small></td><td><span class="badge text-bg-<?=empty($account['last_error'])?'success':'danger'?>"><?=empty($account['last_error'])?'Connecté':'À vérifier'?></span></td><td class="text-end"><?php if(!empty($account['is_user_managed'])&&(int)$account['created_by_user_id']===$userId):?><form method="post" onsubmit="return confirm('Supprimer ce compte personnel ?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$account['id']?>"><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form><?php else:?><span class="text-muted"><i class="bi bi-lock"></i> Géré par l’administrateur</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div><?php endforeach;?>
<div class="modal fade" id="personalAccountModal" tabindex="-1" data-bs-backdrop="static"><div class="modal-dialog modal-lg modal-dialog-scrollable"><form class="modal-content" method="post"><div class="modal-header"><h2 class="modal-title h5">Ajouter un compte personnel</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-7"><label class="form-label">Adresse mail</label><input class="form-control" type="email" name="email_address" required></div><div class="col-md-5"><label class="form-label">Nom affiché</label><input class="form-control" name="display_name"></div><div class="col-md-6"><label class="form-label">Identifiant IMAP/SMTP</label><input class="form-control" name="login_name"></div><div class="col-md-6"><label class="form-label">Mot de passe</label><input class="form-control" type="password" name="password" required></div><div class="col-12"><label class="form-label">Label</label><input class="form-control" name="label_text"></div><div class="col-md-6"><label class="form-label">Serveur IMAP</label><input class="form-control" name="imap_host" required></div><div class="col-md-3"><label class="form-label">Port</label><input class="form-control" type="number" name="imap_port" value="993"></div><div class="col-md-3"><label class="form-label">Sécurité</label><select class="form-select" name="imap_encryption"><option value="ssl">SSL</option><option value="tls">TLS</option><option value="none">Aucune</option></select></div><div class="col-md-6"><label class="form-label">Serveur SMTP</label><input class="form-control" name="smtp_host" required></div><div class="col-md-3"><label class="form-label">Port</label><input class="form-control" type="number" name="smtp_port" value="465"></div><div class="col-md-3"><label class="form-label">Sécurité</label><select class="form-select" name="smtp_encryption"><option value="ssl">SSL</option><option value="tls">TLS</option><option value="none">Aucune</option></select></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Annuler</button><button class="btn btn-danger">Ajouter</button></div></form></div></div>
<?php sodium_render_footer(); ?>
