<?php
return [
    'language'=>'Sprache','language.interface'=>'Sprache der Benutzeroberfläche','language.help'=>'Die Sprache wird sofort auf allen Geräten für Ihr Konto übernommen.','language.updated'=>'Sprache aktualisiert.',
    'common.save'=>'Speichern','common.cancel'=>'Abbrechen','common.close'=>'Schließen','common.continue'=>'Weiter','common.validate'=>'Bestätigen','common.edit'=>'Bearbeiten','common.delete'=>'Löschen','common.add'=>'Hinzufügen','common.search'=>'Suchen','common.download'=>'Herunterladen','common.view'=>'Anzeigen','common.yes'=>'Ja','common.no'=>'Nein','common.all'=>'Alle','common.none'=>'Keine','common.active'=>'Aktiv','common.inactive'=>'Inaktiv','common.status'=>'Status','common.actions'=>'Aktionen','common.name'=>'Name','common.email'=>'E-Mail-Adresse','common.date'=>'Datum','common.subject'=>'Betreff',
    'auth.login.title'=>'Anmelden','auth.identifier'=>'Benutzername oder E-Mail-Adresse','auth.identifier.placeholder'=>'Benutzername, private oder geschäftliche E-Mail','auth.password'=>'Passwort','auth.remember'=>'Angemeldet bleiben','auth.login'=>'Anmelden','auth.lost'=>'Passwort vergessen','auth.twofa'=>'2FA-Code','auth.invalid'=>'Ungültige Anmeldedaten.','auth.required'=>'Bitte geben Sie Ihre Anmeldedaten ein.','auth.rights'=>'Alle Rechte vorbehalten',
    'nav.unified'=>'Gemeinsamer Posteingang','nav.starred'=>'Markierte Nachrichten','nav.outbox'=>'Postausgang','nav.settings'=>'Einstellungen','nav.administration'=>'Administration','nav.accounts'=>'E-Mail-Konten','nav.manage_accounts'=>'E-Mail-Konten verwalten','nav.signatures'=>'Signaturen','nav.tags'=>'Tags','nav.templates'=>'Antwortvorlagen','nav.messages'=>'Nachrichten','nav.users'=>'Benutzer','nav.general'=>'Allgemeine Einstellungen','nav.security'=>'Sicherheitseinstellungen','nav.license'=>'Lizenz','nav.profile'=>'Profil','nav.about'=>'Über','nav.logout'=>'Abmelden','nav.mail_account'=>'E-Mail-Konto','nav.first_account'=>'Erstes Postfach hinzufügen','nav.first_account_help'=>'IMAP- und SMTP-Konto konfigurieren','nav.no_account'=>'Kein E-Mail-Konto zugewiesen','nav.collapse'=>'Menü einklappen',
    'mail.new'=>'Neue Nachricht','mail.refresh'=>'E-Mails abrufen','mail.inbox'=>'Posteingang','mail.drafts'=>'Entwürfe','mail.sent'=>'Gesendet','mail.archives'=>'Archive','mail.trash'=>'Papierkorb','mail.spam'=>'Spam','mail.from'=>'Absender','mail.to'=>'Empfänger','mail.cc'=>'Cc','mail.bcc'=>'Bcc','mail.reply_to'=>'Antwort an','mail.reply'=>'Antworten','mail.reply_all'=>'Allen antworten','mail.forward'=>'Weiterleiten','mail.archive'=>'Archivieren','mail.mark_spam'=>'Spam','mail.move'=>'Verschieben nach','mail.add_tag'=>'Tag hinzufügen','mail.unread'=>'Ungelesen','mail.read'=>'Gelesen','mail.select_all'=>'Alle auswählen','mail.all_tags'=>'Alle Tags','mail.display'=>'Anzeigen','mail.body'=>'Nachricht','mail.attachments'=>'Anhänge','mail.send_now'=>'Jetzt senden','mail.schedule'=>'Versand planen','mail.save_draft'=>'Speichern (Entwurf)','mail.priority'=>'Priorität','mail.normal'=>'Normal','mail.no_subject'=>'(kein Betreff)',
    'profile.title'=>'Profil','profile.information'=>'Meine Informationen','profile.first_name'=>'Vorname','profile.last_name'=>'Nachname','profile.theme'=>'Darstellung','profile.dark'=>'Dunkelmodus','profile.password'=>'Passwort ändern','profile.sessions'=>'Aktive Sitzungen','profile.twofa'=>'Zwei-Faktor-Authentifizierung',
    'install.title'=>'Sodium installieren','install.first_launch'=>'Erster Start','install.welcome'=>'Willkommen bei Sodium Webmail','install.version'=>'Zu installierende Version: :version','install.language'=>'Sprache für Sodium wählen','install.theme'=>'Design des Administratorkontos wählen','install.light'=>'Hell','install.dark'=>'Dunkel','install.dependencies'=>'Abhängigkeiten prüfen','install.license'=>'Softwarelizenz','install.activate'=>'Lizenzaktivierung','install.database'=>'SQL-Datenbankverbindung','install.admin'=>'Administrator und Sicherheit','install.done'=>'Sodium wurde installiert und aktiviert','install.launch'=>'Sodium starten','install.required'=>'Erforderlich','install.valid'=>'Gültig','install.failed'=>'Fehler','install.accept'=>'Akzeptieren und weiter','install.verify_key'=>'Schlüssel prüfen','install.test'=>'Testen und weiter','install.install'=>'Sodium installieren',
];
