<?php
return [
    'language'=>'Language','language.interface'=>'Interface language','language.help'=>'The language is immediately applied to your account on all your devices.','language.updated'=>'Language updated.',
    'common.save'=>'Save','common.cancel'=>'Cancel','common.close'=>'Close','common.continue'=>'Continue','common.validate'=>'Confirm','common.edit'=>'Edit','common.delete'=>'Delete','common.add'=>'Add','common.search'=>'Search','common.download'=>'Download','common.view'=>'View','common.yes'=>'Yes','common.no'=>'No','common.all'=>'All','common.none'=>'None','common.active'=>'Active','common.inactive'=>'Inactive','common.status'=>'Status','common.actions'=>'Actions','common.name'=>'Name','common.email'=>'Email address','common.date'=>'Date','common.subject'=>'Subject',
    'auth.login.title'=>'Sign in','auth.identifier'=>'Username or email address','auth.identifier.placeholder'=>'Username, personal or business email','auth.password'=>'Password','auth.remember'=>'Remember me','auth.login'=>'Sign in','auth.lost'=>'Forgot password','auth.twofa'=>'2FA code','auth.invalid'=>'Invalid credentials.','auth.required'=>'Please enter your credentials.','auth.rights'=>'All rights reserved',
    'nav.unified'=>'Unified inbox','nav.starred'=>'Starred messages','nav.outbox'=>'Outbox','nav.settings'=>'Settings','nav.administration'=>'Administration','nav.accounts'=>'Mail accounts','nav.manage_accounts'=>'Manage mail accounts','nav.signatures'=>'Signatures','nav.tags'=>'Tags','nav.templates'=>'Reply templates','nav.messages'=>'Messages','nav.users'=>'Users','nav.general'=>'General settings','nav.security'=>'Security settings','nav.license'=>'License','nav.profile'=>'Profile','nav.about'=>'About','nav.logout'=>'Sign out','nav.mail_account'=>'Mail account','nav.first_account'=>'Add your first mailbox','nav.first_account_help'=>'Configure an IMAP and SMTP account','nav.no_account'=>'No mail account assigned','nav.collapse'=>'Collapse menu',
    'mail.new'=>'New message','mail.refresh'=>'Check mail','mail.inbox'=>'Inbox','mail.drafts'=>'Drafts','mail.sent'=>'Sent','mail.archives'=>'Archives','mail.trash'=>'Trash','mail.spam'=>'Spam','mail.from'=>'Sender','mail.to'=>'Recipients','mail.cc'=>'Cc','mail.bcc'=>'Bcc','mail.reply_to'=>'Reply to','mail.reply'=>'Reply','mail.reply_all'=>'Reply all','mail.forward'=>'Forward','mail.archive'=>'Archive','mail.mark_spam'=>'Spam','mail.move'=>'Move to','mail.add_tag'=>'Add a tag','mail.unread'=>'Unread','mail.read'=>'Read','mail.select_all'=>'Select all','mail.all_tags'=>'All tags','mail.display'=>'Show','mail.body'=>'Message','mail.attachments'=>'Attachments','mail.send_now'=>'Send now','mail.schedule'=>'Schedule send','mail.save_draft'=>'Save (draft)','mail.priority'=>'Priority','mail.normal'=>'Normal','mail.no_subject'=>'(no subject)',
    'profile.title'=>'Profile','profile.information'=>'My information','profile.first_name'=>'First name','profile.last_name'=>'Last name','profile.theme'=>'Appearance','profile.dark'=>'Dark mode','profile.password'=>'Change password','profile.sessions'=>'Active sessions','profile.twofa'=>'Two-factor authentication',
    'install.title'=>'Install Sodium','install.first_launch'=>'First launch','install.welcome'=>'Welcome to Sodium Webmail','install.version'=>'Version to install: :version','install.language'=>'Choose the Sodium language','install.theme'=>'Choose the administrator account theme','install.light'=>'Light','install.dark'=>'Dark','install.dependencies'=>'Dependency check','install.license'=>'Software license','install.activate'=>'License activation','install.database'=>'SQL database connection','install.admin'=>'Administrator and security','install.done'=>'Sodium is installed and activated','install.launch'=>'Launch Sodium','install.required'=>'Required','install.valid'=>'Valid','install.failed'=>'Failed','install.accept'=>'Accept and continue','install.verify_key'=>'Verify key','install.test'=>'Test and continue','install.install'=>'Install Sodium',
];
