<?php
return [
    'language'=>'Idioma','language.interface'=>'Idioma de la interfaz','language.help'=>'El idioma se aplica inmediatamente a tu cuenta en todos tus dispositivos.','language.updated'=>'Idioma actualizado.',
    'common.save'=>'Guardar','common.cancel'=>'Cancelar','common.close'=>'Cerrar','common.continue'=>'Continuar','common.validate'=>'Confirmar','common.edit'=>'Editar','common.delete'=>'Eliminar','common.add'=>'Añadir','common.search'=>'Buscar','common.download'=>'Descargar','common.view'=>'Ver','common.yes'=>'Sí','common.no'=>'No','common.all'=>'Todos','common.none'=>'Ninguno','common.active'=>'Activo','common.inactive'=>'Inactivo','common.status'=>'Estado','common.actions'=>'Acciones','common.name'=>'Nombre','common.email'=>'Correo electrónico','common.date'=>'Fecha','common.subject'=>'Asunto',
    'auth.login.title'=>'Iniciar sesión','auth.identifier'=>'Usuario o correo electrónico','auth.identifier.placeholder'=>'Usuario, correo personal o profesional','auth.password'=>'Contraseña','auth.remember'=>'Recordarme','auth.login'=>'Iniciar sesión','auth.lost'=>'Contraseña olvidada','auth.twofa'=>'Código 2FA','auth.invalid'=>'Credenciales incorrectas.','auth.required'=>'Introduce tus credenciales.','auth.rights'=>'Todos los derechos reservados',
    'nav.unified'=>'Bandeja unificada','nav.starred'=>'Mensajes destacados','nav.outbox'=>'Bandeja de salida','nav.settings'=>'Ajustes','nav.administration'=>'Administración','nav.accounts'=>'Cuentas de correo','nav.manage_accounts'=>'Gestionar cuentas de correo','nav.signatures'=>'Firmas','nav.tags'=>'Etiquetas','nav.templates'=>'Plantillas de respuesta','nav.messages'=>'Mensajes','nav.users'=>'Usuarios','nav.general'=>'Ajustes generales','nav.security'=>'Ajustes de seguridad','nav.license'=>'Licencia','nav.profile'=>'Perfil','nav.about'=>'Acerca de','nav.logout'=>'Cerrar sesión','nav.mail_account'=>'Cuenta de correo','nav.first_account'=>'Añade tu primer buzón','nav.first_account_help'=>'Configura una cuenta IMAP y SMTP','nav.no_account'=>'Ninguna cuenta de correo asignada','nav.collapse'=>'Contraer menú',
    'mail.new'=>'Nuevo mensaje','mail.refresh'=>'Comprobar correo','mail.inbox'=>'Bandeja de entrada','mail.drafts'=>'Borradores','mail.sent'=>'Enviados','mail.archives'=>'Archivos','mail.trash'=>'Papelera','mail.spam'=>'Correo no deseado','mail.from'=>'Remitente','mail.to'=>'Destinatarios','mail.cc'=>'Cc','mail.bcc'=>'Cco','mail.reply_to'=>'Responder a','mail.reply'=>'Responder','mail.reply_all'=>'Responder a todos','mail.forward'=>'Reenviar','mail.archive'=>'Archivar','mail.mark_spam'=>'Correo no deseado','mail.move'=>'Mover a','mail.add_tag'=>'Añadir etiqueta','mail.unread'=>'No leídos','mail.read'=>'Leídos','mail.select_all'=>'Seleccionar todo','mail.all_tags'=>'Todas las etiquetas','mail.display'=>'Mostrar','mail.body'=>'Mensaje','mail.attachments'=>'Adjuntos','mail.send_now'=>'Enviar ahora','mail.schedule'=>'Programar envío','mail.save_draft'=>'Guardar (borrador)','mail.priority'=>'Prioridad','mail.normal'=>'Normal','mail.no_subject'=>'(sin asunto)',
    'profile.title'=>'Perfil','profile.information'=>'Mi información','profile.first_name'=>'Nombre','profile.last_name'=>'Apellidos','profile.theme'=>'Apariencia','profile.dark'=>'Modo oscuro','profile.password'=>'Cambiar contraseña','profile.sessions'=>'Sesiones activas','profile.twofa'=>'Autenticación de dos factores',
    'install.title'=>'Instalación de Sodium','install.first_launch'=>'Primer inicio','install.welcome'=>'Bienvenido a Sodium Webmail','install.version'=>'Versión a instalar: :version','install.language'=>'Elige el idioma de Sodium','install.theme'=>'Elige el tema de la cuenta administradora','install.light'=>'Claro','install.dark'=>'Oscuro','install.dependencies'=>'Comprobación de dependencias','install.license'=>'Licencia de software','install.activate'=>'Activación de licencia','install.database'=>'Conexión a base de datos SQL','install.admin'=>'Administrador y seguridad','install.done'=>'Sodium está instalado y activado','install.launch'=>'Iniciar Sodium','install.required'=>'Obligatorio','install.valid'=>'Válido','install.failed'=>'Error','install.accept'=>'Aceptar y continuar','install.verify_key'=>'Verificar clave','install.test'=>'Probar y continuar','install.install'=>'Instalar Sodium',
];
