<?php
return [
    'language' => 'Langue', 'language.interface' => 'Langue de l’interface', 'language.help' => 'La langue est appliquée immédiatement à votre compte sur tous vos appareils.', 'language.updated' => 'Langue mise à jour.',
    'common.save' => 'Enregistrer', 'common.cancel' => 'Annuler', 'common.close' => 'Fermer', 'common.continue' => 'Continuer', 'common.validate' => 'Valider', 'common.edit' => 'Modifier', 'common.delete' => 'Supprimer', 'common.add' => 'Ajouter', 'common.search' => 'Rechercher', 'common.download' => 'Télécharger', 'common.view' => 'Voir', 'common.yes' => 'Oui', 'common.no' => 'Non', 'common.all' => 'Tous', 'common.none' => 'Aucun', 'common.active' => 'Actif', 'common.inactive' => 'Inactif', 'common.status' => 'Statut', 'common.actions' => 'Actions', 'common.name' => 'Nom', 'common.email' => 'Adresse mail', 'common.date' => 'Date', 'common.subject' => 'Objet',
    'auth.login.title' => 'Connexion', 'auth.identifier' => 'Utilisateur ou adresse mail', 'auth.identifier.placeholder' => 'Nom utilisateur, email personnel ou professionnel', 'auth.password' => 'Mot de passe', 'auth.remember' => 'Se souvenir de moi', 'auth.login' => 'Se connecter', 'auth.lost' => 'Mot de passe perdu', 'auth.twofa' => 'Code 2FA', 'auth.invalid' => 'Identifiants incorrects.', 'auth.required' => 'Veuillez renseigner vos identifiants.', 'auth.rights' => 'Tous droits réservés',
    'nav.unified' => 'Boîte de réception unifiée', 'nav.starred' => 'Messages marqués', 'nav.outbox' => 'Boîte d’envoi', 'nav.settings' => 'Paramètres', 'nav.administration' => 'Administration', 'nav.accounts' => 'Comptes mails', 'nav.manage_accounts' => 'Gestion Comptes mails', 'nav.signatures' => 'Signatures', 'nav.tags' => 'Tags', 'nav.templates' => 'Modèles de réponses', 'nav.messages' => 'Messages', 'nav.users' => 'Utilisateurs', 'nav.general' => 'Paramètres généraux', 'nav.security' => 'Paramètres de sécurité', 'nav.license' => 'Licence', 'nav.profile' => 'Profil', 'nav.about' => 'À propos', 'nav.logout' => 'Se déconnecter', 'nav.mail_account' => 'Compte mail', 'nav.first_account' => 'Ajouter votre première boîte mail', 'nav.first_account_help' => 'Configurer un compte IMAP et SMTP', 'nav.no_account' => 'Aucun compte mail attribué', 'nav.collapse' => 'Réduire le menu',
    'mail.new' => 'Nouveau message', 'mail.refresh' => 'Relever le courrier', 'mail.inbox' => 'Boîte de réception', 'mail.drafts' => 'Brouillons', 'mail.sent' => 'Envoyés', 'mail.archives' => 'Archives', 'mail.trash' => 'Corbeille', 'mail.spam' => 'Indésirables', 'mail.from' => 'Expéditeur', 'mail.to' => 'Destinataires', 'mail.cc' => 'Cc', 'mail.bcc' => 'Cci', 'mail.reply_to' => 'Répondre à', 'mail.reply' => 'Répondre', 'mail.reply_all' => 'Répondre à tous', 'mail.forward' => 'Transférer', 'mail.archive' => 'Archiver', 'mail.mark_spam' => 'Indésirable', 'mail.move' => 'Déplacer vers', 'mail.add_tag' => 'Ajouter un tag', 'mail.unread' => 'Non lus', 'mail.read' => 'Lus', 'mail.select_all' => 'Tout sélectionner', 'mail.all_tags' => 'Tous les tags', 'mail.display' => 'Afficher', 'mail.body' => 'Message', 'mail.attachments' => 'Pièces jointes', 'mail.send_now' => 'Envoyer maintenant', 'mail.schedule' => 'Programmer l’envoi', 'mail.save_draft' => 'Enregistrer (brouillon)', 'mail.priority' => 'Priorité', 'mail.normal' => 'Normale', 'mail.no_subject' => '(pas d’objet)',
    'profile.title' => 'Profil', 'profile.information' => 'Mes informations', 'profile.first_name' => 'Prénom', 'profile.last_name' => 'Nom', 'profile.theme' => 'Apparence', 'profile.dark' => 'Mode sombre', 'profile.password' => 'Modifier le mot de passe', 'profile.sessions' => 'Sessions actives', 'profile.twofa' => 'Authentification à deux facteurs',
    'install.title' => 'Installation de Sodium', 'install.first_launch' => 'Premier lancement', 'install.welcome' => 'Bienvenue dans Sodium Webmail', 'install.version' => 'Version à installer : :version', 'install.language' => 'Choisissez la langue de Sodium', 'install.theme' => 'Choisissez le thème du compte administrateur', 'install.light' => 'Clair', 'install.dark' => 'Sombre', 'install.dependencies' => 'Vérification des dépendances', 'install.license' => 'Licence d’exploitation', 'install.activate' => 'Activation de la licence', 'install.database' => 'Connexion à la base SQL', 'install.admin' => 'Administrateur et sécurité', 'install.done' => 'Sodium est installé et activé', 'install.launch' => 'Lancer Sodium', 'install.required' => 'Obligatoire', 'install.valid' => 'Valide', 'install.failed' => 'Échec', 'install.accept' => 'Accepter et continuer', 'install.verify_key' => 'Vérifier la clé', 'install.test' => 'Tester et continuer', 'install.install' => 'Installer Sodium',
];
