<?php
return [
    'language'=>'Lingua','language.interface'=>'Lingua dell’interfaccia','language.help'=>'La lingua viene applicata immediatamente al tuo account su tutti i dispositivi.','language.updated'=>'Lingua aggiornata.',
    'common.save'=>'Salva','common.cancel'=>'Annulla','common.close'=>'Chiudi','common.continue'=>'Continua','common.validate'=>'Conferma','common.edit'=>'Modifica','common.delete'=>'Elimina','common.add'=>'Aggiungi','common.search'=>'Cerca','common.download'=>'Scarica','common.view'=>'Visualizza','common.yes'=>'Sì','common.no'=>'No','common.all'=>'Tutti','common.none'=>'Nessuno','common.active'=>'Attivo','common.inactive'=>'Inattivo','common.status'=>'Stato','common.actions'=>'Azioni','common.name'=>'Nome','common.email'=>'Indirizzo email','common.date'=>'Data','common.subject'=>'Oggetto',
    'auth.login.title'=>'Accedi','auth.identifier'=>'Nome utente o indirizzo email','auth.identifier.placeholder'=>'Nome utente, email personale o aziendale','auth.password'=>'Password','auth.remember'=>'Ricordami','auth.login'=>'Accedi','auth.lost'=>'Password dimenticata','auth.twofa'=>'Codice 2FA','auth.invalid'=>'Credenziali non valide.','auth.required'=>'Inserisci le tue credenziali.','auth.rights'=>'Tutti i diritti riservati',
    'nav.unified'=>'Posta in arrivo unificata','nav.starred'=>'Messaggi contrassegnati','nav.outbox'=>'Posta in uscita','nav.settings'=>'Impostazioni','nav.administration'=>'Amministrazione','nav.accounts'=>'Account email','nav.manage_accounts'=>'Gestione account email','nav.signatures'=>'Firme','nav.tags'=>'Tag','nav.templates'=>'Modelli di risposta','nav.messages'=>'Messaggi','nav.users'=>'Utenti','nav.general'=>'Impostazioni generali','nav.security'=>'Impostazioni di sicurezza','nav.license'=>'Licenza','nav.profile'=>'Profilo','nav.about'=>'Informazioni','nav.logout'=>'Esci','nav.mail_account'=>'Account email','nav.first_account'=>'Aggiungi la prima casella email','nav.first_account_help'=>'Configura un account IMAP e SMTP','nav.no_account'=>'Nessun account email assegnato','nav.collapse'=>'Riduci menu',
    'mail.new'=>'Nuovo messaggio','mail.refresh'=>'Controlla posta','mail.inbox'=>'Posta in arrivo','mail.drafts'=>'Bozze','mail.sent'=>'Inviati','mail.archives'=>'Archivi','mail.trash'=>'Cestino','mail.spam'=>'Indesiderata','mail.from'=>'Mittente','mail.to'=>'Destinatari','mail.cc'=>'Cc','mail.bcc'=>'Ccn','mail.reply_to'=>'Rispondi a','mail.reply'=>'Rispondi','mail.reply_all'=>'Rispondi a tutti','mail.forward'=>'Inoltra','mail.archive'=>'Archivia','mail.mark_spam'=>'Indesiderata','mail.move'=>'Sposta in','mail.add_tag'=>'Aggiungi tag','mail.unread'=>'Non letti','mail.read'=>'Letti','mail.select_all'=>'Seleziona tutto','mail.all_tags'=>'Tutti i tag','mail.display'=>'Mostra','mail.body'=>'Messaggio','mail.attachments'=>'Allegati','mail.send_now'=>'Invia ora','mail.schedule'=>'Programma invio','mail.save_draft'=>'Salva (bozza)','mail.priority'=>'Priorità','mail.normal'=>'Normale','mail.no_subject'=>'(nessun oggetto)',
    'profile.title'=>'Profilo','profile.information'=>'Le mie informazioni','profile.first_name'=>'Nome','profile.last_name'=>'Cognome','profile.theme'=>'Aspetto','profile.dark'=>'Modalità scura','profile.password'=>'Cambia password','profile.sessions'=>'Sessioni attive','profile.twofa'=>'Autenticazione a due fattori',
    'install.title'=>'Installazione di Sodium','install.first_launch'=>'Primo avvio','install.welcome'=>'Benvenuto in Sodium Webmail','install.version'=>'Versione da installare: :version','install.language'=>'Scegli la lingua di Sodium','install.theme'=>'Scegli il tema dell’account amministratore','install.light'=>'Chiaro','install.dark'=>'Scuro','install.dependencies'=>'Verifica dipendenze','install.license'=>'Licenza software','install.activate'=>'Attivazione licenza','install.database'=>'Connessione database SQL','install.admin'=>'Amministratore e sicurezza','install.done'=>'Sodium è installato e attivato','install.launch'=>'Avvia Sodium','install.required'=>'Obbligatorio','install.valid'=>'Valido','install.failed'=>'Errore','install.accept'=>'Accetta e continua','install.verify_key'=>'Verifica chiave','install.test'=>'Testa e continua','install.install'=>'Installa Sodium',
];
