<?php
return [
    'language'=>'Idioma','language.interface'=>'Idioma da interface','language.help'=>'O idioma é aplicado imediatamente à sua conta em todos os dispositivos.','language.updated'=>'Idioma atualizado.',
    'common.save'=>'Guardar','common.cancel'=>'Cancelar','common.close'=>'Fechar','common.continue'=>'Continuar','common.validate'=>'Confirmar','common.edit'=>'Editar','common.delete'=>'Eliminar','common.add'=>'Adicionar','common.search'=>'Pesquisar','common.download'=>'Transferir','common.view'=>'Ver','common.yes'=>'Sim','common.no'=>'Não','common.all'=>'Todos','common.none'=>'Nenhum','common.active'=>'Ativo','common.inactive'=>'Inativo','common.status'=>'Estado','common.actions'=>'Ações','common.name'=>'Nome','common.email'=>'Endereço de email','common.date'=>'Data','common.subject'=>'Assunto',
    'auth.login.title'=>'Iniciar sessão','auth.identifier'=>'Utilizador ou endereço de email','auth.identifier.placeholder'=>'Utilizador, email pessoal ou profissional','auth.password'=>'Palavra-passe','auth.remember'=>'Lembrar-me','auth.login'=>'Iniciar sessão','auth.lost'=>'Esqueci a palavra-passe','auth.twofa'=>'Código 2FA','auth.invalid'=>'Credenciais inválidas.','auth.required'=>'Introduza as suas credenciais.','auth.rights'=>'Todos os direitos reservados',
    'nav.unified'=>'Caixa de entrada unificada','nav.starred'=>'Mensagens marcadas','nav.outbox'=>'Caixa de saída','nav.settings'=>'Definições','nav.administration'=>'Administração','nav.accounts'=>'Contas de email','nav.manage_accounts'=>'Gerir contas de email','nav.signatures'=>'Assinaturas','nav.tags'=>'Etiquetas','nav.templates'=>'Modelos de resposta','nav.messages'=>'Mensagens','nav.users'=>'Utilizadores','nav.general'=>'Definições gerais','nav.security'=>'Definições de segurança','nav.license'=>'Licença','nav.profile'=>'Perfil','nav.about'=>'Sobre','nav.logout'=>'Terminar sessão','nav.mail_account'=>'Conta de email','nav.first_account'=>'Adicione a primeira caixa de correio','nav.first_account_help'=>'Configure uma conta IMAP e SMTP','nav.no_account'=>'Nenhuma conta de email atribuída','nav.collapse'=>'Recolher menu',
    'mail.new'=>'Nova mensagem','mail.refresh'=>'Verificar correio','mail.inbox'=>'Caixa de entrada','mail.drafts'=>'Rascunhos','mail.sent'=>'Enviados','mail.archives'=>'Arquivos','mail.trash'=>'Lixo','mail.spam'=>'Spam','mail.from'=>'Remetente','mail.to'=>'Destinatários','mail.cc'=>'Cc','mail.bcc'=>'Bcc','mail.reply_to'=>'Responder a','mail.reply'=>'Responder','mail.reply_all'=>'Responder a todos','mail.forward'=>'Reencaminhar','mail.archive'=>'Arquivar','mail.mark_spam'=>'Spam','mail.move'=>'Mover para','mail.add_tag'=>'Adicionar etiqueta','mail.unread'=>'Não lidas','mail.read'=>'Lidas','mail.select_all'=>'Selecionar tudo','mail.all_tags'=>'Todas as etiquetas','mail.display'=>'Mostrar','mail.body'=>'Mensagem','mail.attachments'=>'Anexos','mail.send_now'=>'Enviar agora','mail.schedule'=>'Agendar envio','mail.save_draft'=>'Guardar (rascunho)','mail.priority'=>'Prioridade','mail.normal'=>'Normal','mail.no_subject'=>'(sem assunto)',
    'profile.title'=>'Perfil','profile.information'=>'As minhas informações','profile.first_name'=>'Nome','profile.last_name'=>'Apelido','profile.theme'=>'Aspeto','profile.dark'=>'Modo escuro','profile.password'=>'Alterar palavra-passe','profile.sessions'=>'Sessões ativas','profile.twofa'=>'Autenticação de dois fatores',
    'install.title'=>'Instalação do Sodium','install.first_launch'=>'Primeiro arranque','install.welcome'=>'Bem-vindo ao Sodium Webmail','install.version'=>'Versão a instalar: :version','install.language'=>'Escolha o idioma do Sodium','install.theme'=>'Escolha o tema da conta de administrador','install.light'=>'Claro','install.dark'=>'Escuro','install.dependencies'=>'Verificação de dependências','install.license'=>'Licença de software','install.activate'=>'Ativação da licença','install.database'=>'Ligação à base de dados SQL','install.admin'=>'Administrador e segurança','install.done'=>'O Sodium está instalado e ativado','install.launch'=>'Iniciar Sodium','install.required'=>'Obrigatório','install.valid'=>'Válido','install.failed'=>'Falha','install.accept'=>'Aceitar e continuar','install.verify_key'=>'Verificar chave','install.test'=>'Testar e continuar','install.install'=>'Instalar Sodium',
];
