<?php
declare(strict_types=1);

function e(mixed $value):string{return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');}
function redirect(string $path):never{header('Location: '.$path);exit;}
function current_user():?array{static $cache=false;if(is_array($cache))return $cache;global $pdo;if(empty($_SESSION['user_id']))remember_login_from_cookie();if(empty($_SESSION['user_id']))return null;$stmt=$pdo->prepare("SELECT * FROM users WHERE id=? AND account_status='active'");$stmt->execute([(int)$_SESSION['user_id']]);$user=$stmt->fetch()?:null;if(!$user)unset($_SESSION['user_id']);return $cache=$user;}
function require_login():void{$user=current_user();if(!$user)redirect('/login.php?redirect='.urlencode((string)($_SERVER['REQUEST_URI']??'/index.php')));$script=(string)($_SERVER['SCRIPT_NAME']??'');if(!empty($user['twofa_required'])&&empty($user['twofa_enabled'])&&!in_array($script,['/profile.php','/logout.php'],true)){flash('warning','Vous devez configurer l’authentification à deux facteurs avant de continuer.');redirect('/profile.php');}}
function cookie_secure_flag():bool{return true;}
function set_sodium_cookie(string $name,string $value,int $expires):void{setcookie($name,$value,['expires'=>$expires,'path'=>'/','secure'=>true,'httponly'=>true,'samesite'=>'Lax']);}
function ensure_user_sessions_table():void{static $done=false;if($done)return;global $pdo;$pdo->exec("CREATE TABLE IF NOT EXISTS user_sessions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,selector CHAR(32) NOT NULL UNIQUE,token_hash CHAR(64) NOT NULL,user_agent VARCHAR(500) NULL,ip_address VARCHAR(45) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,last_used_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at DATETIME NOT NULL,INDEX idx_sessions_user(user_id),INDEX idx_sessions_expires(expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$pdo->exec('DELETE FROM user_sessions WHERE expires_at<NOW()');$done=true;}
function current_remember_selector():string{if(!empty($_SESSION['remember_session_selector']))return(string)$_SESSION['remember_session_selector'];$cookie=(string)($_COOKIE[REMEMBER_COOKIE_NAME]??'');return preg_match('/^([a-f0-9]{32}):[a-f0-9]{64}$/',$cookie,$m)?$m[1]:'';}
function issue_remember_cookie(int $userId):void{global $pdo;ensure_user_sessions_table();$selector=bin2hex(random_bytes(16));$token=bin2hex(random_bytes(32));$expires=time()+REMEMBER_COOKIE_DAYS*86400;$pdo->prepare('INSERT INTO user_sessions(user_id,selector,token_hash,user_agent,ip_address,expires_at) VALUES(?,?,?,?,?,FROM_UNIXTIME(?))')->execute([$userId,$selector,hash('sha256',$token),mb_substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,500),mb_substr((string)($_SERVER['REMOTE_ADDR']??''),0,45),$expires]);$_SESSION['remember_session_selector']=$selector;set_sodium_cookie(REMEMBER_COOKIE_NAME,$selector.':'.$token,$expires);}
function clear_remember_cookie(?int $userId=null,bool $allDevices=false):void{global $pdo;ensure_user_sessions_table();if($userId&&$allDevices)$pdo->prepare('DELETE FROM user_sessions WHERE user_id=?')->execute([$userId]);else{$selector=current_remember_selector();if($selector!=='')$pdo->prepare('DELETE FROM user_sessions WHERE selector=?')->execute([$selector]);}unset($_SESSION['remember_session_selector']);set_sodium_cookie(REMEMBER_COOKIE_NAME,'',time()-3600);}
function remember_login_from_cookie():void{global $pdo;ensure_user_sessions_table();$cookie=(string)($_COOKIE[REMEMBER_COOKIE_NAME]??'');if(!preg_match('/^([a-f0-9]{32}):([a-f0-9]{64})$/',$cookie,$m))return;$stmt=$pdo->prepare("SELECT s.* FROM user_sessions s JOIN users u ON u.id=s.user_id AND u.account_status='active' WHERE selector=? LIMIT 1");$stmt->execute([$m[1]]);$session=$stmt->fetch();if(!$session||strtotime((string)$session['expires_at'])<time()||!hash_equals((string)$session['token_hash'],hash('sha256',$m[2]))){clear_remember_cookie();return;}session_regenerate_id(true);$_SESSION['user_id']=(int)$session['user_id'];$_SESSION['remember_session_selector']=$m[1];}
function base32_encode_no_padding(string $data):string{$alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';foreach(str_split($data)as$c)$bits.=str_pad(decbin(ord($c)),8,'0',STR_PAD_LEFT);$out='';foreach(str_split($bits,5)as$chunk)$out.=$alphabet[bindec(str_pad($chunk,5,'0',STR_PAD_RIGHT))];return$out;}
function base32_decode_no_padding(string $secret):string{$alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';foreach(str_split(strtoupper(preg_replace('/[^A-Z2-7]/','',$secret)))as$c){$p=strpos($alphabet,$c);if($p!==false)$bits.=str_pad(decbin($p),5,'0',STR_PAD_LEFT);}$out='';foreach(str_split($bits,8)as$chunk)if(strlen($chunk)===8)$out.=chr(bindec($chunk));return$out;}
function twofa_generate_secret():string{return base32_encode_no_padding(random_bytes(20));}
function twofa_code_for_counter(string $secret,int $counter):string{$hash=hash_hmac('sha1',pack('N*',0).pack('N*',$counter),base32_decode_no_padding($secret),true);$offset=ord(substr($hash,-1))&15;$value=unpack('N',substr($hash,$offset,4))[1]&0x7fffffff;return str_pad((string)($value%1000000),6,'0',STR_PAD_LEFT);}
function twofa_verify_code(string $secret,string $code):bool{$code=preg_replace('/\s+/','',$code);if(!preg_match('/^\d{6}$/',$code))return false;$counter=(int)floor(time()/30);for($i=-3;$i<=3;$i++)if(hash_equals(twofa_code_for_counter($secret,$counter+$i),$code))return true;return false;}
function twofa_otpauth_uri(array $user,string $secret):string{$label=rawurlencode('Sodium:'.($user['email']?:$user['username']));return'otpauth://totp/'.$label.'?secret='.rawurlencode($secret).'&issuer=Sodium&algorithm=SHA1&digits=6&period=30';}
function flash(?string $type=null,?string $message=null):array{if($type!==null&&$message!==null){$_SESSION['flash'][$type]=$message;return[];}$messages=(array)($_SESSION['flash']??[]);unset($_SESSION['flash']);return$messages;}
function verify_turnstile(?string $token):bool{$secret=function_exists('sodium_turnstile_secret_key')?sodium_turnstile_secret_key():(defined('TURNSTILE_SECRET_KEY')?(string)TURNSTILE_SECRET_KEY:'');if(!$token||$secret==='')return false;$curl=curl_init('https://challenges.cloudflare.com/turnstile/v0/siteverify');curl_setopt_array($curl,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>10,CURLOPT_POSTFIELDS=>http_build_query(['secret'=>$secret,'response'=>$token,'remoteip'=>$_SERVER['REMOTE_ADDR']??''])]);$response=curl_exec($curl);curl_close($curl);$data=json_decode((string)$response,true);return is_array($data)&&!empty($data['success']);}
function nav_active(string $path):string{return($_SERVER['SCRIPT_NAME']??'')===$path?'active':'';}
function table_exists_local(string $table):bool{global $pdo;$stmt=$pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$stmt->execute([$table]);return(bool)$stmt->fetchColumn();}
function user_has_aptitude(string $label,?int $userId=null):bool{return function_exists('sodium_can')&&sodium_can($label);}
