<?php
declare(strict_types=1);
$root=dirname(__DIR__);$configFile=$root.'/config.local.php';$installedFile=$root.'/.installed';$requestedStep=(int)($_GET['step']??1);$installVersion='0.9.4 bêta';
header('Strict-Transport-Security: max-age=31536000; includeSubDomains');header('X-Frame-Options: DENY');header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');header('Cache-Control: no-store');session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>true,'httponly'=>true,'samesite'=>'Strict']);session_start();
if(is_file($installedFile)&&!($requestedStep===7&&!empty($_SESSION['install_complete']))){header('Location: /login.php');exit;}
if(empty($_SESSION['install_csrf']))$_SESSION['install_csrf']=bin2hex(random_bytes(32));
$https=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')||strtolower((string)($_SERVER['HTTP_X_FORWARDED_PROTO']??''))==='https';
$requirements=['PHP 8.2 ou supérieur'=>PHP_VERSION_ID>=80200,'Extension IMAP'=>extension_loaded('imap'),'Extension PDO MySQL'=>extension_loaded('pdo_mysql'),'Extension OpenSSL'=>extension_loaded('openssl'),'Extension cURL'=>extension_loaded('curl'),'Extension Mbstring'=>extension_loaded('mbstring'),'Extension Fileinfo'=>extension_loaded('fileinfo'),'Extension ZIP'=>extension_loaded('zip'),'Extension JSON'=>extension_loaded('json'),'Extension Iconv'=>extension_loaded('iconv'),'Écriture de la configuration'=>is_writable($root)];
$step=max(1,min(7,(int)($_GET['step']??1)));$error='';
function h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function install_csrf():void{if(!hash_equals((string)($_SESSION['install_csrf']??''),(string)($_POST['csrf']??'')))throw new RuntimeException('Session d’installation expirée.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  install_csrf();$action=(string)($_POST['action']??'');
  if($action==='welcome'){$theme=(string)($_POST['theme']??'');if(!in_array($theme,['light','dark'],true))throw new RuntimeException('Choisissez un thème.');$_SESSION['install_theme']=$theme;header('Location: ?step=2');exit;}
  if($action==='environment'){if(!$https)throw new RuntimeException('HTTPS doit être actif avant de poursuivre.');if(in_array(false,$requirements,true))throw new RuntimeException('Un prérequis serveur est manquant.');$_SESSION['install_environment_checked']=1;header('Location: ?step=3');exit;}
  if($action==='accept_license'){if(empty($_POST['accept_license']))throw new RuntimeException('Vous devez lire et accepter la licence pour poursuivre.');$_SESSION['install_license_accepted_at']=date(DATE_ATOM);header('Location: ?step=4');exit;}
  if($action==='license_key'){
   if(empty($_SESSION['install_license_accepted_at']))throw new RuntimeException('La licence doit d’abord être acceptée.');$licenseKey=strtolower(trim((string)($_POST['license_key']??'')));if(!preg_match('/^[a-f0-9]{128}$/',$licenseKey))throw new RuntimeException('La clé doit contenir exactement 128 caractères hexadécimaux.');
   $domain=strtolower((string)($_SERVER['HTTP_HOST']??''));$curl=curl_init('https://licence.jessysystem.com/');curl_setopt_array($curl,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>12,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Accept: application/json'],CURLOPT_POSTFIELDS=>json_encode(['license_key'=>$licenseKey,'product_slug'=>'sodium-webmail','domain'=>$domain,'version'=>'0.9.4'])]);$body=curl_exec($curl);$code=(int)curl_getinfo($curl,CURLINFO_RESPONSE_CODE);curl_close($curl);$verification=$code===200?json_decode((string)$body,true):null;if(!is_array($verification)||($verification['status']??'')!=='ok')throw new RuntimeException('Cette clé n’est pas valide ou le domaine '.$domain.' ne lui est pas exclusivement affecté.');$_SESSION['install_license_key']=$licenseKey;$_SESSION['install_license_verification']=$verification;header('Location: ?step=5');exit;
  }
  if($action==='database'){
   $db=['host'=>trim((string)($_POST['db_host']??'localhost')),'name'=>trim((string)($_POST['db_name']??'')),'user'=>trim((string)($_POST['db_user']??'')),'pass'=>(string)($_POST['db_pass']??'')];
   if($db['name']===''||$db['user']==='')throw new RuntimeException('Renseignez la base et son utilisateur.');
   $test=new PDO('mysql:host='.$db['host'].';dbname='.$db['name'].';charset=utf8mb4',$db['user'],$db['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
   $exists=(int)$test->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='users'")->fetchColumn();
   if($exists&&(int)$test->query('SELECT COUNT(*) FROM users')->fetchColumn()>0)throw new RuntimeException('Cette base contient déjà des utilisateurs. Utilisez une base vide pour éviter toute prise de contrôle accidentelle.');
   $_SESSION['install_db']=$db;header('Location: ?step=6');exit;
  }
  if($action==='install'){
   $db=$_SESSION['install_db']??null;$licenseKey=(string)($_SESSION['install_license_key']??'');$licenseVerification=$_SESSION['install_license_verification']??null;if(!is_array($db))throw new RuntimeException('Recommencez la vérification SQL.');if($licenseKey===''||!is_array($licenseVerification))throw new RuntimeException('Recommencez la validation de la licence.');
   $username=trim((string)($_POST['username']??''));$first=trim((string)($_POST['first_name']??''));$last=trim((string)($_POST['last_name']??''));$email=trim((string)($_POST['email']??''));$password=(string)($_POST['password']??'');
   if(!preg_match('/^[a-zA-Z0-9._-]{3,80}$/',$username))throw new RuntimeException('Identifiant administrateur invalide.');if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Adresse mail invalide.');if(strlen($password)<12)throw new RuntimeException('Le mot de passe doit contenir au moins 12 caractères.');if(!hash_equals($password,(string)($_POST['password_confirm']??'')))throw new RuntimeException('Les mots de passe ne correspondent pas.');
   $baseUrl='https://'.strtolower((string)($_SERVER['HTTP_HOST']??'sodium.jessysystem.ovh'));
   $turnstileEnabled=!empty($_POST['turnstile_enabled']);
   $config=['db_host'=>$db['host'],'db_name'=>$db['name'],'db_user'=>$db['user'],'db_pass'=>$db['pass'],'base_url'=>$baseUrl,'app_name'=>'Sodium','timezone'=>(string)($_POST['timezone']??'Europe/Paris'),'turnstile_enabled'=>$turnstileEnabled,'turnstile_site_key'=>$turnstileEnabled?trim((string)($_POST['turnstile_site_key']??'')):'','turnstile_secret_key'=>$turnstileEnabled?trim((string)($_POST['turnstile_secret_key']??'')):'','cron_token'=>bin2hex(random_bytes(32)),'license_accepted_at'=>(string)$_SESSION['install_license_accepted_at']];
   if($turnstileEnabled&&($config['turnstile_site_key']===''||$config['turnstile_secret_key']===''))throw new RuntimeException('Renseignez les deux clés Cloudflare Turnstile ou désactivez cette protection.');
   $pdo=new PDO('mysql:host='.$db['host'].';dbname='.$db['name'].';charset=utf8mb4',$db['user'],$db['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
   $pdo->exec("CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(80) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,first_name VARCHAR(100) NOT NULL DEFAULT '',last_name VARCHAR(100) NOT NULL DEFAULT '',email VARCHAR(190) NOT NULL UNIQUE,professional_email VARCHAR(190) NULL,address_line1 VARCHAR(190) NOT NULL DEFAULT '',address_line2 VARCHAR(190) NOT NULL DEFAULT '',postal_code VARCHAR(20) NOT NULL DEFAULT '',city VARCHAR(100) NOT NULL DEFAULT '',phone VARCHAR(40) NOT NULL DEFAULT '',birth_date DATE NULL,birth_place VARCHAR(120) NOT NULL DEFAULT '',social_security_number VARCHAR(40) NOT NULL DEFAULT '',gender CHAR(1) NULL,role VARCHAR(30) NOT NULL DEFAULT 'user',account_status VARCHAR(20) NOT NULL DEFAULT 'active',is_active TINYINT(1) NOT NULL DEFAULT 1,theme VARCHAR(10) NOT NULL DEFAULT 'light',twofa_required TINYINT(1) NOT NULL DEFAULT 0,twofa_enabled TINYINT(1) NOT NULL DEFAULT 0,twofa_secret VARCHAR(100) NULL,last_login_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
   if((int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn()>0)throw new RuntimeException('La base n’est plus vide. Installation interrompue.');
   $mailKeyFile=$root.'/.sodium-mail-key';if(!is_file($mailKeyFile)){file_put_contents($mailKeyFile,bin2hex(random_bytes(32))."\n",LOCK_EX);chmod($mailKeyFile,0600);}define('DB_PASS',$db['pass']);require_once $root.'/includes/platform/functions.php';require_once $root.'/includes/sodium.php';sodium_ensure_schema();sodium_store_license($licenseKey,$licenseVerification);
   $stmt=$pdo->prepare("INSERT INTO users(id,username,password_hash,first_name,last_name,email,professional_email,role,account_status,is_active,theme) VALUES(1,?,?,?,?,?,?,'admin','active',1,?)");$stmt->execute([$username,password_hash($password,PASSWORD_DEFAULT),$first,$last,$email,$email,(string)($_SESSION['install_theme']??'dark')]);
   $export="<?php\ndeclare(strict_types=1);\nreturn ".var_export($config,true).";\n";$tmp=$configFile.'.tmp';if(file_put_contents($tmp,$export,LOCK_EX)===false)throw new RuntimeException('Impossible d’écrire la configuration.');chmod($tmp,0600);if(!rename($tmp,$configFile))throw new RuntimeException('Impossible de finaliser la configuration.');file_put_contents($installedFile,date(DATE_ATOM)."\n",LOCK_EX);chmod($installedFile,0600);unset($_SESSION['install_db'],$_SESSION['install_license_key'],$_SESSION['install_license_verification']);$_SESSION['install_complete']=1;header('Location: ?step=7');exit;
  }
 }catch(Throwable $e){$error=$e->getMessage();}
}
if($step>=2&&empty($_SESSION['install_theme'])){header('Location: ?step=1');exit;}
if($step>=3&&empty($_SESSION['install_environment_checked'])){header('Location: ?step=2');exit;}
if($step>=4&&empty($_SESSION['install_license_accepted_at'])){header('Location: ?step=3');exit;}
if($step>=5&&empty($_SESSION['install_license_key'])){header('Location: ?step=4');exit;}
if($step>=6&&$step<7&&empty($_SESSION['install_db'])){header('Location: ?step=5');exit;}
?><!doctype html><html lang="fr" data-bs-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Installation de Sodium</title><link href="/assets/vendor/bootstrap/bootstrap.min.css" rel="stylesheet"><link href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet"><link href="/css/app.css?v=20260729-01" rel="stylesheet"><style>body{min-height:100vh;display:grid;place-items:center;background:#0b1120}.installer{width:min(920px,calc(100% - 2rem))}.step{width:2rem;height:2rem;border-radius:50%;display:grid;place-items:center;background:#374151;color:#fff}.step.active{background:#dc3545;color:#fff}[data-bs-theme=light] .step{background:#64748b;color:#fff}[data-bs-theme=light] .step.active{background:#dc3545}.license-text{max-height:330px;overflow:auto;white-space:normal}.theme-option input{position:absolute;opacity:0}.theme-option span{display:block;border:1px solid var(--bs-border-color);border-radius:.75rem;padding:1rem;text-align:center}.theme-option input:checked+span{border-color:#dc3545;box-shadow:0 0 0 .2rem rgba(220,53,69,.2)}</style></head><body><main class="installer"><div class="card shadow-lg"><div class="card-body p-4 p-lg-5"><div class="d-flex align-items-center gap-3 mb-4"><span class="brand-mark text-white">M</span><div><div class="text-danger text-uppercase small fw-bold">Premier lancement</div><h1 class="h3 mb-0">Installation de Sodium</h1></div></div><div class="d-flex gap-3 mb-4"><?php for($i=1;$i<=7;$i++):?><span class="step <?=$step===$i?'active':''?>"><?=$i?></span><?php endfor;?></div><?php if($error):?><div class="alert alert-danger"><i class="bi bi-exclamation-octagon me-2"></i><?=h($error)?></div><?php endif;?>
<?php if($step===1):?><div class="text-center mb-4"><i class="bi bi-envelope-check text-danger display-3"></i><h2 class="mt-3">Bienvenue dans Sodium Webmail</h2><div class="mb-3"><code>Version à installer : <?=h($installVersion)?></code></div><p class="lead mb-2">Sodium est un webmail professionnel conçu pour centraliser, organiser et sécuriser la gestion de plusieurs comptes de messagerie depuis une interface unique.</p><p class="text-muted">Il réunit les boîtes de réception, dossiers, conversations, pièces jointes, signatures, tags, modèles de réponses, envois programmés et notifications. Plusieurs utilisateurs peuvent collaborer selon des habilitations précises.</p></div><form method="post"><input type="hidden" name="csrf" value="<?=h($_SESSION['install_csrf'])?>"><input type="hidden" name="action" value="welcome"><h3 class="h5 mb-3">Choisissez le thème du compte administrateur</h3><div class="row g-3 mb-4"><div class="col-6"><label class="theme-option d-block"><input type="radio" name="theme" value="light" required><span><i class="bi bi-sun fs-2 d-block mb-2"></i><strong>Clair</strong></span></label></div><div class="col-6"><label class="theme-option d-block"><input type="radio" name="theme" value="dark" checked><span><i class="bi bi-moon-stars fs-2 d-block mb-2"></i><strong>Sombre</strong></span></label></div></div><button class="btn btn-danger w-100">Continuer</button></form>
<?php elseif($step===2):?><h2 class="h5">Vérification des dépendances</h2><p class="text-muted">Sodium contrôle les fonctions nécessaires à la connexion SQL, à la relève IMAP, aux envois, aux pièces jointes et au chiffrement.</p><div class="list-group mb-4"><div class="list-group-item d-flex justify-content-between">Connexion HTTPS <span class="badge text-bg-<?=$https?'success':'danger'?>"><?=$https?'Valide':'Obligatoire'?></span></div><?php foreach($requirements as $label=>$ok):?><div class="list-group-item d-flex justify-content-between"><?=h($label)?><span class="badge text-bg-<?=$ok?'success':'danger'?>"><?=$ok?'OK':'Échec'?></span></div><?php endforeach;?></div><form method="post"><input type="hidden" name="csrf" value="<?=h($_SESSION['install_csrf'])?>"><input type="hidden" name="action" value="environment"><button class="btn btn-danger w-100" <?=$https&&!in_array(false,$requirements,true)?'':'disabled'?>>Continuer</button></form>
<?php elseif($step===3):?><h2 class="h5">Licence d’exploitation</h2><div class="license-text border rounded p-4 bg-body-tertiary mb-4"><h3 class="h6">Droits concédés</h3><p>Sodium est un logiciel SaaS conçu, édité et maintenu par <strong>Jessy System</strong>. Son utilisation est exclusivement autorisée dans le périmètre d’une licence valide concédée à l’ayant droit et pour le domaine enregistré.</p><h3 class="h6">Propriété intellectuelle</h3><p>Le logiciel, son architecture, son code, ses interfaces, ses textes, ses éléments graphiques et ses bases de données sont protégés par le droit d’auteur et les règles françaises, européennes et internationales relatives à la propriété intellectuelle. La licence ne transfère aucun droit de propriété.</p><h3 class="h6">Interdictions</h3><p>Toute utilisation sans licence valide ou hors de son périmètre, reproduction, modification, diffusion, adaptation, rétro-ingénierie, décompilation, sous-licence, partage de clé ou contournement du contrôle de licence est strictement interdit sans l’accord préalable, exprès et écrit de Jessy System.</p><h3 class="h6">Protection des droits</h3><p>Tout usage irrégulier peut entraîner la suspension immédiate du logiciel, la réparation intégrale du préjudice subi et toute action civile ou pénale appropriée. Les conditions contractuelles particulières conclues avec Jessy System prévalent en cas de contradiction.</p></div><form method="post"><input type="hidden" name="csrf" value="<?=h($_SESSION['install_csrf'])?>"><input type="hidden" name="action" value="accept_license"><label class="border rounded p-3 mb-3 d-flex align-items-start gap-3"><input class="form-check-input flex-shrink-0 m-0 mt-1" type="checkbox" name="accept_license" value="1" required><span>J’ai lu et j’accepte sans réserve les conditions de la licence d’exploitation Sodium.</span></label><button class="btn btn-danger w-100">Accepter et continuer</button></form>
<?php elseif($step===4):?><h2 class="h5">Activation de la licence</h2><div class="alert alert-info"><i class="bi bi-globe2 me-2"></i>Le domaine détecté <code><?=h(strtolower((string)($_SERVER['HTTP_HOST']??'')))?></code> doit être exclusivement affecté à cette clé dans le gestionnaire de licences Jessy System.</div><p class="text-muted">La clé sera vérifiée pour ce domaine puis stockée sous forme chiffrée.</p><form method="post"><input type="hidden" name="csrf" value="<?=h($_SESSION['install_csrf'])?>"><input type="hidden" name="action" value="license_key"><label class="form-label">Clé de licence</label><textarea class="form-control font-monospace" name="license_key" rows="4" minlength="128" maxlength="128" spellcheck="false" required></textarea><button class="btn btn-danger w-100 mt-3"><i class="bi bi-key me-2"></i>Vérifier la clé</button></form>
<?php elseif($step===5):?><h2 class="h5">Connexion à la base SQL</h2><div class="alert alert-info"><strong>Une base MySQL ou MariaDB est obligatoire.</strong><div class="small mt-1">Droits requis uniquement sur la base Sodium : <code>ALTER, CREATE, DELETE, INSERT, SELECT, UPDATE</code>.</div></div><form method="post" class="row g-3"><input type="hidden" name="csrf" value="<?=h($_SESSION['install_csrf'])?>"><input type="hidden" name="action" value="database"><div class="col-md-6"><label class="form-label">Hôte SQL</label><input class="form-control" name="db_host" value="localhost" required></div><div class="col-md-6"><label class="form-label">Nom de la base</label><input class="form-control" name="db_name" required></div><div class="col-md-6"><label class="form-label">Utilisateur SQL</label><input class="form-control" name="db_user" required></div><div class="col-md-6"><label class="form-label">Mot de passe SQL</label><input class="form-control" type="password" name="db_pass"></div><div class="col-12"><button class="btn btn-danger w-100">Tester et continuer</button></div></form>
<?php elseif($step===6):?><h2 class="h5">Administrateur et sécurité</h2><form method="post" class="row g-3"><input type="hidden" name="csrf" value="<?=h($_SESSION['install_csrf'])?>"><input type="hidden" name="action" value="install"><div class="col-md-4"><label class="form-label">Identifiant</label><input class="form-control" name="username" required></div><div class="col-md-4"><label class="form-label">Prénom</label><input class="form-control" name="first_name" required></div><div class="col-md-4"><label class="form-label">Nom</label><input class="form-control" name="last_name" required></div><div class="col-12"><label class="form-label">Adresse mail</label><input class="form-control" type="email" name="email" required></div><div class="col-md-6"><label class="form-label">Mot de passe (12 caractères minimum)</label><input class="form-control" type="password" name="password" minlength="12" required></div><div class="col-md-6"><label class="form-label">Confirmation</label><input class="form-control" type="password" name="password_confirm" minlength="12" required></div><div class="col-12"><div class="border rounded p-3"><div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" role="switch" id="turnstileEnabled" name="turnstile_enabled" value="1" checked><label class="form-check-label" for="turnstileEnabled"><strong>Activer Cloudflare Turnstile <span class="badge text-bg-success ms-1">Vivement recommandé</span></strong><small class="d-block text-muted mt-1">Sodium utilise Turnstile pour protéger la connexion et la récupération de mot de passe contre les robots et les tentatives automatisées. Cette protection peut être désactivée, mais réduit alors le niveau de sécurité de l’instance.</small></label></div></div></div><div class="col-12" id="turnstileKeys"><div class="row g-3"><div class="col-md-6"><label class="form-label">Clé de site Turnstile</label><input class="form-control" name="turnstile_site_key" required></div><div class="col-md-6"><label class="form-label">Clé secrète Turnstile</label><input class="form-control" type="password" name="turnstile_secret_key" required></div></div></div><div class="col-12"><input type="hidden" name="timezone" value="Europe/Paris"><button class="btn btn-danger w-100">Installer Sodium</button></div></form>
<?php else:?><div class="text-center py-4"><i class="bi bi-check-circle-fill text-success display-3"></i><h2 class="mt-3">Sodium est installé et activé</h2><p class="text-muted">La configuration et la licence sont enregistrées. Le wizard est désormais verrouillé.</p><a class="btn btn-danger px-5" href="/login.php">Lancer Sodium</a></div><?php endif;?></div></div></main><script>(()=>{const choices=document.querySelectorAll('input[name="theme"]'),apply=value=>document.documentElement.setAttribute('data-bs-theme',value);choices.forEach(choice=>choice.addEventListener('change',()=>apply(choice.value)));const checked=document.querySelector('input[name="theme"]:checked');if(checked)apply(checked.value);const toggle=document.getElementById('turnstileEnabled'),keys=document.getElementById('turnstileKeys');if(toggle&&keys){const sync=()=>{keys.hidden=!toggle.checked;keys.querySelectorAll('input').forEach(input=>{input.disabled=!toggle.checked;input.required=toggle.checked;});};toggle.addEventListener('change',sync);sync();}})();</script></body></html>
