<?php
/** @var array $message */
$account=$message['account'];
$messageFolder=(string)($message['folder']??'INBOX');
$selection=base64_encode(json_encode(['account'=>(int)$account['id'],'folder'=>$messageFolder,'uid'=>(int)$message['uid'],'key'=>$message['message_key']]));
?>
<div class="message-row unified <?= $message['unread'] ? 'unread' : '' ?>" data-message-row data-account="<?= (int)$account['id'] ?>" data-folder="<?= e($messageFolder) ?>" data-uid="<?= (int)$message['uid'] ?>">
    <span class="message-select-tools"><input class="form-check-input message-checkbox" type="checkbox" name="messages[]" value="<?= e($selection) ?>"><button class="message-star <?= $message['flagged']?'is-flagged':'' ?>" type="button" data-star-toggle title="<?= $message['flagged']?'Retirer des messages marqués':'Ajouter aux messages marqués' ?>"><i class="bi bi-star<?= $message['flagged']?'-fill':'' ?>"></i></button></span>
    <span class="message-account-identity"><?php if (!empty($account['icon_path'])): ?><img class="mail-account-image" style="--account-color:<?= e($account['label_color']) ?>" src="<?= e($account['icon_path']) ?>" alt=""><?php else: ?><span class="mail-account-avatar" style="--account-color:<?= e($account['label_color']) ?>"><?= e(strtoupper(substr((string)$account['email_address'],0,1))) ?></span><?php endif; ?><?php if(!empty($account['label_text'])): ?><span class="mailbox-label" style="--label-color:<?= e($account['label_color']) ?>;--label-text-color:<?= e(sodium_color_contrast((string)$account['label_color'])) ?>"><?= e($account['label_text']) ?></span><?php endif; ?></span>
    <span class="message-sender"><?= e($message['from']) ?></span>
    <span class="message-subject"><button class="read-dot <?= $message['unread']?'is-unread':'' ?>" type="button" title="<?= $message['unread']?'Marquer comme lu':'Marquer comme non lu' ?>" data-read-toggle></button><?php if($message['has_attachment']): ?><i class="bi bi-paperclip message-attachment-icon" title="Ce message contient une pièce jointe"></i><?php endif; ?><button class="message-open" type="button" data-open-message><?= e($message['subject']) ?></button><?php if(!empty($showSearchFolder)&&strcasecmp($messageFolder,'INBOX')!==0): ?><span class="badge text-bg-secondary deep-search-folder"><?= e((string)($message['folder_label']??sodium_folder_display_label($messageFolder))) ?></span><?php endif; ?><?php foreach($message['metadata']['tags']??[] as $tag): ?><span class="mail-tag" style="--tag-color:<?= e($tag['color']) ?>"><?= e($tag['name']) ?></span><?php endforeach; ?><?php if(!empty($message['metadata']['replies'])):$names=array_unique(array_column($message['metadata']['replies'],'name')); ?><i class="bi bi-reply-fill replied-icon" title="Répondu par <?= e(implode(', ',$names)) ?>"></i><?php endif; ?></span>
    <time class="message-date human-date" tabindex="0" data-timestamp="<?= (int)$message['timestamp'] ?>" data-human="<?= e(sodium_human_date($message['timestamp'])) ?>" data-exact="<?= e($message['date']) ?>"><?= e(sodium_human_date($message['timestamp'])) ?></time>
</div>
